/** @author Joseph Manno AKA OblativeShielding */
package com.oblativeshielding.pizzanburgers;

import java.io.IOException;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

/**
 * The primary application class.
 * 
 * <p> This class contains the main method of the program, and maintains the JavaFX application
 * elements behind the scenes. Most of the actual functionality is run in RootScene, however.
 */
public class PizzaNBurgers extends Application {

  private static Scene scene;

  /**
   * Begins the program using JavaFX.
   */
  @Override
  public void start(Stage stage) throws IOException {
    scene = new Scene(loadFXML("rootScene"), 700, 480);
    stage.setScene(scene);
    stage.setTitle("Pizza'N'Burgers");
    stage.show();
  }

  /**
   * Sets the root scene to the given fxml filename.
   * 
   * @author Auto-generated by VSCode
   */
  public static void setRoot(String fxml) throws IOException {
    scene.setRoot(loadFXML(fxml));
  }

  /**
   * Loads the given filename from fxml.
   * 
   * @return a Parent object loaded from the given fxml filename
   */
  private static Parent loadFXML(String fxml) throws IOException {
    FXMLLoader fxmlLoader = new FXMLLoader(PizzaNBurgers.class.getResource("fxml/" + fxml + ".fxml"));
    return fxmlLoader.load();
  }

  /**
   * Runs the program.
   */
  public static void main(String[] args) {
    launch();
  }

}